---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"WHAT'S this?" I pondered. "Have I slept?      
Or can I have been drinking?"  
But soon a gentler feeling crept    
Upon me, and I sat and wept  
An hour or so, like winking.   

## Second Verse 
<!--Put the first five lines of a poem by Robert Frost here!-->

My long two-pointed ladder's sticking through a tree   
Toward heaven still,  
And there's a barrel that I didn't fill   
Beside it, and there may be two or three  
Apples I didn't pick upon some bough.  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright --  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done --  
'It's very rude of him.' she said,  
'To come and spoil the fun!'  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

In stature the Manlet was dwarfish--  
No burly, big Blunderbore he;  
And he wearily gazed on the crawfish  
His Wifelet had dressed for his tea.  
'Now reach me, sweet Atom, my gunlet,  
And hurl the old shoelet for luck;  
Let me hie to the bank of the runlet,  
And shoot thee a Duck!'  

She has reached him his minikin gunlet;  
She has hurled the old shoelet for luck;  
She is busily baking a bunlet,  
To welcome him home with his Duck.  